---
image: python:3.6

stages:
  - syntax
  - analysis and tests
  - ci-deploy
  - ci-test
  - ci-deprovision

flake8:
  stage: syntax
  script:
    - pip install flake8
    - flake8 --extend-ignore E722,W605 pebbles

analysis-and-tests:
  stage: analysis and tests
  # cache pip downloads and installed packages
  variables:
      PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - .cache/pip
      - venv/
  script:
    - pip install -r requirements.txt
    - python manage.py test
    - pip install pylint
    - "pylint -j0 pebbles || true" # no failures ATM

ci-deploy:
  stage: ci-deploy
  image: $CI_REGISTRY/pebbles/pebbles-deploy/pebbles-deployer
  variables:
    ENV_NAME: pebbles-ci-2
  script:
    - /opt/deployment/init_env.bash
    # build, deploy and initialize
    - source /opt/deployment/deploy_functions.bash
    - install-pebbles $CI_COMMIT_REF_NAME

ci-test:
  stage: ci-test
  image: $CI_REGISTRY/pebbles/pebbles-deploy/pebbles-deployer
  variables:
    ENV_NAME: pebbles-ci-2
  script:
    - /opt/deployment/init_env.bash
    # tests
    - curl https://pebbles-ci-2.rahti-int-app.csc.fi/api/v1/config | grep INSTALLATION_NAME
    - oc rsh deployment/api python manage.py test

ci-deprovision:
  stage: ci-deprovision
  image: $CI_REGISTRY/pebbles/pebbles-deploy/pebbles-deployer
  variables:
    ENV_NAME: pebbles-ci-2
  when: always
  script:
    - /opt/deployment/init_env.bash
    # uninstall and cleanup
    - helm uninstall pebbles
    - oc delete secret pebbles
    # remove logstash volume that is normally left behind
    - "(oc get pvc logstash && oc delete pvc logstash) || true"
