language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

# for new container based Travis environment
sudo: false

addons:
  apt:
    packages:
    - graphviz
install:
- pip install --upgrade "pip<8"
- pip --version
- pip install -r requirements.txt
- pip install flake8==3.2.0
- pip install .

before_script:
- flake8 pebbles

script:
- python manage.py test
- travis-sphinx --branches=master --source=doc/source build

# Whose tokens are these? In the future document crypted tokens when you add
# them!
notifications:
  flowdock:
    secure: VteCDhr47oT0S2kST2s755cYJMVZachfn+utiPAasqxTiaFb+ZpxB7jR9Dt6BTIyPTkxfVYGpfJv8+6sM72ezQNETu6XmwCatQvVIQ8S5jdSb5uW6jv+0bcZbyBfK+D6xzEG/yBjy6UZGdwhYDmf+aUd1RR1GAzl6BBDtvRP3Vk=

# travis-sphinx requires an OAuth token, this is stored under the settings of the Pebbles repo on Travis CI website.
after_success:
- travis-sphinx --branches=master deploy
