---

- name: Fetch application from Github
  git: repo={{ git_repository }} version={{ git_version }} dest={{ application_path }}
  when: deploy_mode == "standalone"

- name: Link shared directory content to application_path from Docker shared directory
  file: src={{ shared_folder_path }}/source dest={{ application_path }} state=link
  when: deploy_mode == "docker"

# TODO: unify this with docker deployment
- name: Link shared directory content to application_path
  file: src={{ shared_folder_path }} dest={{ application_path }} state=link
  when: deploy_mode == "devel"

- name: Install dependencies from requirements.txt
  pip: requirements={{ application_path }}/requirements.txt virtualenv={{ virtualenv_path }}

- name: Install infrastructural dependencies from PyPI
  pip: name={{ item }} virtualenv={{ virtualenv_path }}
  with_items:
      - gunicorn
