---

- name: Create the Apache configuration file
  template: src=etc/apache2/sites-available/pouta-blueprints-ssl.j2
            dest=/etc/apache2/sites-available/{{ application_name }}-ssl.conf
            backup=yes

- name: Create the Apache configuration file for HTTP redirect
  template: src=etc/apache2/sites-available/pouta-blueprints.j2
            dest=/etc/apache2/sites-available/{{ application_name }}.conf
            backup=yes

- name: Ensure that the default site is disabled
  command: rm /etc/apache2/sites-enabled/000-default.conf
           removes=/etc/apache2/sites-enabled/000-default.conf

- name: Enable application site with SSL
  command: a2ensite {{ application_name }}-ssl
           creates=/etc/apache2/sites-enabled/{{ application_name }}-ssl.conf

- name: Enable redirect from non-SSL to SSL
  command: a2ensite {{ application_name }}
           creates=/etc/apache2/sites-enabled/{{ application_name }}.conf

- name: Install shib2 module for Apache
  apt: pkg=libapache2-mod-shib2 state=present
  when: enable_shibboleth == "True"

- name: Enable required Apache modules
  apache2_module: state=present name={{ item }}
  with_items:
      - proxy
      - proxy_http
      - ssl

- name: Enable Apache Shibboleth module
  apache2_module: state=present name=shib2
  when: enable_shibboleth == "True"


- name: Link static root for Apache
  file:
    src={{ application_path }}/{{ application_name }}/static
    dest={{ apache_static_root }}
    state=link
    # mode=775
    # owner={{ application_user }}
    # group={{ application_group }}

- name: Create provisioning log file root directory
  file:
    dest={{ apache_log_file_root }}
    mode=755 state=directory
    owner={{ application_user }}
    group={{ application_group }}

- name: Create ssl dir
  file:
    dest={{ apache_ssl_cert_dir }}
    owner=root
    group=root
    mode=0600
    state=directory

- name: Create self-signed SSL cert
  command: 
    openssl req -new -nodes -x509 -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain }}" -days 3650 -keyout {{ apache_ssl_key }} -out {{ apache_ssl_crt }} -extensions v3_ca 
    creates={{ apache_ssl_crt }}
  notify: restart apache
