---
- name: Create the Supervisor config file for www
  template: src=etc/supervisor/supervisor_config_common_services.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-common_services.conf
            backup=yes

- name: Create the Supervisor config file for nginx on www
  template: src=etc/supervisor/supervisor_config_nginx.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-nginx.conf
            backup=yes
  when: web_server_type == "nginx"


- name: Create the Supervisor config file for www (devel)
  template: src=etc/supervisor/supervisor_config_devserver.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-application.conf
            backup=yes
  when: server_type == "devel"

- name: Create the Supervisor config file for www (prod)
  template: src=etc/supervisor/supervisor_config_gunicorn.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-application.conf
            backup=yes
  when: server_type == "prod"

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
