apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            {% if egressBlockCidr is defined %}
            except:
              - "{{ egressBlockCidr }}"
            {% endif %}
