apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{name}}"
spec:
  host: "{{host}}"
  to:
    name: "{{name}}"
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
