---

- name: Install package dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - redis-server


- name: ensure database is created
  sudo_user: postgres
  postgresql_db: name={{application_database_name}}

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_user: db={{application_database_name}} name={{application_database_user}} password={{application_database_password}} priv=ALL

- name: Install psycopg from pip to virtualenv
  pip: name={{ item }} virtualenv={{ virtualenv_path }}
  with_items:
      - psycopg2

- name: Set redis to listen to all interfaces
  lineinfile:
    name=/etc/redis/redis.conf
    regexp='^bind.*'
    state=absent

- name: Set redis not to daemonize
  shell: sed -i 's/^\(daemonize\s*\)yes\s*$/\1no/g' /etc/redis/redis.conf

- name: Disable redis-server on boot and make sure it is stopped - supervisord takes care of this
  service:
    name=redis-server
    enabled=false
    state=stopped

- include: setup_runtime_directories.yml
- include: setup_supervisor_config.yml
